// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqfhqkwwdibcnhkdzlhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxZmhxa3d3ZGliY25oa2R6bGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MDg2MTEsImV4cCI6MjA1MDE4NDYxMX0.uXISmIGL9pUAsLfnhk0Rqq94J_0KfSHrcPTmVWCMiTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);