// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsrjyryrxfruexcwbxea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzcmp5cnlyeGZydWV4Y3dieGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MDc5OTQsImV4cCI6MjA1MDE4Mzk5NH0.9dtVjievquwHssAZKkdtGPK-agb159WVDOd38OXvZ5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);